apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql1
  template:
    metadata:
      labels:
        app: mysql1
    spec:
      containers:
        - name: mysql1
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: S0mmerInsp1red
          ports:
            - containerPort: 3306
              name: mysql1
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mysql1
spec:
  selector:
    app: mysql1
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 31236
  type: NodePort

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mysql1-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host:
      http:
        paths:
          - backend:
              serviceName: mysql1
              servicePort: 31236
            path: /mysql