---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atm-module3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atm-module3
  template:
    metadata:
      labels:
        app: atm-module3
    spec:
      containers:
        - name: atm-module3
          image: shmuelhalbfinger/practiceatmbankapp:atm-module3
          ports:
            - containerPort: 8080
              name: atm-module
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: atm-module3
spec:
  selector:
    app: atm-module3
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31238
      protocol: TCP
  type: NodePort