

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atm-module
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atm-module
  template:
    metadata:
      labels:
        app: atm-module
    spec:
      containers:
        - name: atm-module
          image: shmuelhalbfinger/practiceatmbankapp:atm-module
          ports:
            - containerPort: 8080
              name: atm-module
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: atm-module
spec:
  selector:
    app: atm-module
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31235
      protocol: TCP
  type: NodePort